steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "$$PASSWORD" | docker login --username=$$USERNAME --password-stdin
    secretEnv: ["USERNAME", "PASSWORD"]

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        DOCKER_BUILDKIT=1 docker build -t $$USERNAME/$_IMAGE_NAME:$COMMIT_SHA .
    secretEnv: ["USERNAME"]

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker push $$USERNAME/$_IMAGE_NAME:$COMMIT_SHA
    secretEnv: ["USERNAME"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy $_SERVICE_NAME \
        --image docker.io/$$USERNAME/$_IMAGE_NAME:$COMMIT_SHA \
        --region $_REGION \
        --platform managed \
        --cpu $_CPU \
        --memory $_MEMORY \
        --concurrency $_CONCURRENCY \
        --min-instances $_MIN_INSTANCES \
        --max-instances $_MAX_INSTANCES \
        --set-env-vars ENV=PROD,ENABLE_SECTION_CACHE=1,WEB_CONCURRENCY=$_WEB_CONCURRENCY
    secretEnv: ["USERNAME"]

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/docker-username/versions/1
      env: "USERNAME"
    - versionName: projects/$PROJECT_ID/secrets/docker-password/versions/1
      env: "PASSWORD"

substitutions:
  _SERVICE_NAME: scraper
  _REGION: us-central1
  _IMAGE_NAME: schedule-maker-scraper
  _CPU: "2"
  _MEMORY: "1Gi"
  _CONCURRENCY: "120"
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "20"
  _WEB_CONCURRENCY: "1"
